force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CalculateTotalProjectsBudget.cls
@RestResource(urlMapping='/Project/*')
global with sharing class CalculateTotalProjectsBudget {
  @HttpGet
  global static Double getTotalBudget() {
    // Perform the aggregate query
    AggregateResult[] results = [
      SELECT SUM(Budget__c) total
      FROM Project__c
      WHERE Status__c = 'In Progress'
      GROUP BY Status__c
    ];

    // Extract the sum from the aggregate result
    Double totalSum = 0;
    if (!results.isEmpty()) {
      totalSum = (Double) results[0].get('total');
    }
    return totalSum;
  }
}